-   id: detect-dicom
    name: "Detect DICOM files."
    description: "Detects the presence of DICOM files which might contain sensitive information."
    entry: detect-dicom
    language: python
    types: [binary]
    # args: []
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
-   id: detect-file-corruption
    name: "Detect corrupted files."
    description: "Detects corrupted files using various integrity tests."
    entry: detect-file-corruption
    language: python
    types: [binary,text]
    # args: []
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
